# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HashTest
ARDUINO_LIBS := AUnit AceCommon
include ../../../UnixHostDuino/UnixHostDuino.mk
