# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := GenericStatsTest
ARDUINO_LIBS := AUnit AceCommon
include ../../../EpoxyDuino/EpoxyDuino.mk
