# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := Udiv1000
ARDUINO_LIBS := AceCommon
include ../../../EpoxyDuino/EpoxyDuino.mk
